GRANT USAGE ON SCHEMA scratch TO "apps";
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA scratch TO "apps";
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA scratch TO "apps";
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA scratch TO "apps";